### ISSUE TITLE
Button+CSS3=Good Button

### ISSUE THREAD

**Issue by Netrinix** [rocky-co/notebook#2]
网上看见有个特别棒的按钮，就复制了下来。
CSS:
```css
button .rocky ui buttons {
  margin-bottom: 10px;
  height: 25px;
  background-color: #55c4d0;
  border: none;
  box-shadow: 0 1px 5px #55c4d0;
  outline: none;
  cursor: pointer;
  color: #fff;
}

.rocky ui buttons button:active {
  transform: scale(0.8);
}
```
用button标签，class为rocky ui buttons
为了方便大家给多个按钮添加此特效，使用了Class属性—___—
